### ISSUE TITLE
一直停留在下载中

### ISSUE THREAD

**Issue by StrollStars** [chansLam/m3u8_downloader#1]
![2021-11-06_135734](https://user-images.githubusercontent.com/10942225/140599697-671162b5-ba99-4c23-bb67-574e9703a35f.jpg)
如图

PS：左上角红框中的词写错了。

**Comment by chansLam** [comment]
最近工作比较忙，这个软件暂时不支持在html中解析到m3u8的下载地址，需要你使用F12找到m3u8的连接。同时这个软件有个BUG，连接必须带一个问号
例如：https://tspc.vvvdj.com/c1/2021/11/221865-83e065/221865.m3u8?upt=9a61357a1638892799&news
